script: cd src && make
language: c
compiler:
        - clang
        - gcc
os:
        - linux
        - os
addons:
  apt:
    packages:
      - graphviz
script:
        - cd src
        - make
        - make test
        - make jpg
