script: cd src && make
language: c
compiler:
- clang
- gcc
os:
- linux
- osx
addons:
  apt:
    packages:
      - graphviz
before_script:
- printenv
- echo "executing before_script"
- [ "$TRAVIS_OS_NAME" = "osx" ] && brew install graphviz
script:
- cd src
- make all
